POST http://localhost:3333/classes
content-type: application/json

{
    "name": "Gomes",
    "avatar": "https://avatars0.githubusercontent.com/u/40321477?s=460&u=46c06fde645ce124e446b99e6acda08664f66550&v=4",
    "whatsapp": "55341999999",
    "bio": "Él cabrón mas fascinado por religion del velho-oeste",
    "subject": "Religião",
    "cost": 80,
    "schedule": [
        { "week_day": 1, "from": "8:00", "to":"18:00" },
        { "week_day": 2, "from": "8:00", "to":"18:00" },
        { "week_day": 3, "from": "8:00", "to":"18:00" },
        { "week_day": 4, "from": "8:00", "to":"18:00" },
        { "week_day": 5, "from": "8:00", "to":"18:00" }
    ]
}

###

GET http://localhost:3333/classes
    ?week_day=6
    &subject=Matemática
    &time=18:00


###

POST http://localhost:3333/connections
content-type: application/json

{
    "user_id": 1
}


###

GET http://localhost:3333/connections